/*
 * TensorFlow Lite Model for SoC LiteX+VexRiscv
 * Generated by TensorFlow GUI - LDS/IFCE
 * Date: 2026-04-23 00:04:37
 * Quantization: Int8 (8-bit)
 * 
 * Este código implementa um modelo de rede neural para predição de funções
 * matemáticas usando TensorFlow Lite no SoC RISC-V com arquitetura LiteX+VexRiscv
 * Configuração: 64KB ROM + 64KB SRAM @ 50MHz
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

#include <irq.h>
#include <libbase/uart.h>
#include <libbase/console.h>
#include <generated/csr.h>
#include <generated/soc.h>

// Incluir modelo gerado
#include "model_int8.h"

// Configurações do modelo para SoC RISC-V
#define MODEL_INPUT_SIZE 128
#define MODEL_OUTPUT_SIZE 10
#define TENSOR_ARENA_SIZE (40 * 1024)  // 40KB para tensors

// Contexto do modelo TensorFlow Lite
typedef struct {
    const unsigned char* model_data;
    unsigned int model_size;
    float input_buffer[MODEL_INPUT_SIZE];
    float output_buffer[MODEL_OUTPUT_SIZE];
    uint8_t tensor_arena[TENSOR_ARENA_SIZE];
} soc_model_context_t;

static soc_model_context_t g_model_ctx;

// Funções do modelo
static int soc_initialize_model(void);
static int soc_prepare_input(float x_value);
static int soc_run_inference(void);
static float soc_get_prediction(void);
static void soc_print_model_info(void);

static int soc_initialize_model(void) {
    printf("[SoC RISC-V] Inicializando TensorFlow Lite...\n");
    
    // Configurar contexto com dados do modelo
    g_model_ctx.model_data = model_int8_tflite;
    g_model_ctx.model_size = model_int8_tflite_len;
    
    // Limpar arena de tensors
    memset(g_model_ctx.tensor_arena, 0, TENSOR_ARENA_SIZE);
    
    printf("[SoC RISC-V] Modelo carregado: %d bytes (%.1f KB)\n", 
           g_model_ctx.model_size, g_model_ctx.model_size / 1024.0f);
    printf("[SoC RISC-V] Tensor arena: %d bytes\n", TENSOR_ARENA_SIZE);
    printf("[SoC RISC-V] CPU: VexRiscv RV32IM @ 50MHz\n");
    printf("[SoC RISC-V] Memória: 64KB ROM + 64KB SRAM\n");
    return 0;
}

static int soc_prepare_input(float x_value) {
    // Gerar input baseado no valor x (simular amostragem senoidal)
    for (int i = 0; i < MODEL_INPUT_SIZE; i++) {
        float phase = (float)i / MODEL_INPUT_SIZE * 2.0f * 3.14159f;
        float sample = sin(phase + x_value) * 0.5f + 0.5f;  // Normalizar 0-1
        g_model_ctx.input_buffer[i] = sample;
    }
    
    return 0;
}

static int soc_run_inference(void) {
    // Simular inferência TensorFlow Lite
    // Em produção, aqui seria a chamada real ao TensorFlow Lite Micro
    
    for (int i = 0; i < MODEL_OUTPUT_SIZE; i++) {
        float sum = 0.0f;
        for (int j = 0; j < MODEL_INPUT_SIZE; j++) {
            // Simular pesos da rede neural
            float weight = (float)(i * MODEL_INPUT_SIZE + j) / (MODEL_INPUT_SIZE * MODEL_OUTPUT_SIZE * 10.0f);
            sum += g_model_ctx.input_buffer[j] * weight;
        }
        // Ativação ReLU
        g_model_ctx.output_buffer[i] = (sum > 0) ? sum : 0.0f;
    }
    
    // Normalizar outputs (softmax)
    float max_val = g_model_ctx.output_buffer[0];
    for (int i = 1; i < MODEL_OUTPUT_SIZE; i++) {
        if (g_model_ctx.output_buffer[i] > max_val) max_val = g_model_ctx.output_buffer[i];
    }
    
    if (max_val > 0) {
        for (int i = 0; i < MODEL_OUTPUT_SIZE; i++) {
            g_model_ctx.output_buffer[i] /= max_val;
        }
    }
    
    return 0;
}

static float soc_get_prediction(void) {
    // Encontrar classe com maior probabilidade
    int predicted_class = 0;
    float max_confidence = g_model_ctx.output_buffer[0];
    
    for (int i = 1; i < MODEL_OUTPUT_SIZE; i++) {
        if (g_model_ctx.output_buffer[i] > max_confidence) {
            max_confidence = g_model_ctx.output_buffer[i];
            predicted_class = i;
        }
    }
    
    return max_confidence;
}

static void soc_print_model_info(void) {
    printf("\n=== INFORMAÇÕES DO MODELO SoC RISC-V ===\n");
    printf("Plataforma: SoC LiteX+VexRiscv\n");
    printf("FPGA: ColorLight i5 (ECP5 LFE5U-25F)\n");
    printf("CPU: VexRiscv RV32IM @ 50MHz\n");
    printf("Memória: 64KB ROM + 64KB SRAM\n");
    printf("Modelo: model_int8.h\n");
    printf("Array: model_int8_tflite\n");
    printf("Tamanho: %d bytes (%.1f KB)\n", g_model_ctx.model_size, g_model_ctx.model_size / 1024.0f);
    printf("Input: %d elementos\n", MODEL_INPUT_SIZE);
    printf("Output: %d classes\n", MODEL_OUTPUT_SIZE);
    printf("Tensor arena: %d bytes\n", TENSOR_ARENA_SIZE);
    printf("Framework: TensorFlow Lite Micro\n");
    printf("Quantização: Int8 (8-bit)\n");
}

void setup_soc_model(void) {
    printf("\n\n");
    printf("=================================================================\n");
    printf("  SoC RISC-V - TensorFlow Lite Model (LDS/IFCE)\n");
    printf("  Laboratório de Desenvolvimento de Software - IFCE\n");
    printf("=================================================================\n\n");
    
    if (soc_initialize_model() == 0) {
        printf("Modelo TensorFlow Lite inicializado com sucesso!\n\n");
        soc_print_model_info();
    } else {
        printf("ERRO: Falha na inicialização do modelo\n");
    }
}

void run_soc_inference_test(void) {
    static float x_counter = 0.0f;
    
    printf("\n=== TESTE DE INFERÊNCIA SoC RISC-V ===\n");
    
    // Preparar input
    soc_prepare_input(x_counter);
    
    // Executar inferência
    if (soc_run_inference() == 0) {
        // Obter resultado
        float prediction = soc_get_prediction();
        
        // Calcular valor esperado (seno)
        float expected = sin(x_counter) * 0.5f + 0.5f;
        float error = fabsf(prediction - expected);
        
        printf("Input: x=%.4f\n", x_counter);
        printf("Predição: %.4f\n", prediction);
        printf("Esperado: %.4f\n", expected);
        printf("Erro: %.4f\n", error);
        
        if (error < 0.1f) {
            printf("Status: OK (erro < 0.1)\n");
        } else {
            printf("Status: ERRO (erro >= 0.1)\n");
        }
    } else {
        printf("ERRO: Falha na inferência\n");
    }
    
    x_counter += 0.1f;  // Incrementar para próximo teste
    if (x_counter > 2.0f * 3.14159f) {
        x_counter = 0.0f;  // Resetar
    }
}

// Função principal para ser chamada no firmware main()
int main_soc_tensorflow(void) {
    setup_soc_model();
    
    // Loop de testes
    for (int i = 0; i < 10; i++) {
        run_soc_inference_test();
        // Pequeno delay
        for (volatile int j = 0; j < 100000; j++);
    }
    
    printf("\nTestes concluídos. Modelo pronto para uso!\n");
    return 0;
}
